import type { Difficulty, ModelOption, MorfoItem, PeriphrasisItem, SeItem } from "./types";

export const MODEL_OPTIONS: ModelOption[] = [
  { label: "Gemini 2.5 Flash Lite", value: "gemini-2.5-flash-lite" },
  { label: "Gemini 2.5 Flash", value: "gemini-2.5-flash" },
  { label: "Gemini 2.5 Pro", value: "gemini-2.5-pro" },
  { label: "Gemini 2.0 Flash", value: "gemini-2.0-flash" },
  { label: "Gemini 2.0 Flash Exp", value: "gemini-2.0-flash-exp" },
  { label: "Gemini 2.0 Flash Lite", value: "gemini-2.0-flash-lite" },
  { label: "Gemma 3 1B IT", value: "gemma-3-1b-it" },
  { label: "Gemma 3 4B IT", value: "gemma-3-4b-it" },
  { label: "Gemma 3 12B IT", value: "gemma-3-12b-it" },
  { label: "Gemma 3 27B IT", value: "gemma-3-27b-it" },
];

export const SE_VALUES = [
  "Reflexivo",
  "Reciproco",
  "Sustitucion (le -> se)",
  "Pronominal",
  "Pasiva refleja",
  "Impersonal",
  "Accidental (dativo de interes)",
] as const;

export const SE_FUNCTIONS = [
  "CD",
  "CI",
  "Sin funcion sintactica propia",
  "Morfema verbal",
  "Marca de pasiva",
  "Marca de impersonal",
] as const;

export const SE_VERBAL_STRUCTURES = [
  "Verbo simple",
  "Perifrasis verbal",
  "Locucion verbal",
  "Dos verbos",
] as const;

export const SE_PERIPHRASIS_TYPES = [
  "No aplica",
  "Modal obligativa",
  "Modal de posibilidad",
  "Aspectual ingresiva",
  "Aspectual incoativa",
  "Aspectual durativa",
  "Aspectual terminativa",
  "Aspectual reiterativa",
  "Aspectual resultativa",
  "Aspectual habitual",
] as const;

export const MORFO_WORD_TYPES = ["Sustantivo", "Adjetivo", "Verbo", "Adverbio"] as const;

export const PERIPHRASIS_STRUCTURES = [
  "Perifrasis verbal",
  "Locucion verbal",
  "Dos verbos",
] as const;

export const PERIPHRASIS_TYPES = [
  "No aplica",
  "Modal obligativa",
  "Modal de posibilidad",
  "Aspectual ingresiva",
  "Aspectual incoativa",
  "Aspectual durativa",
  "Aspectual terminativa",
  "Aspectual reiterativa",
  "Aspectual resultativa",
  "Aspectual habitual",
] as const;

export const MORFO_MORPHEME_TYPES = [
  "Prefijo derivativo",
  "Interfijo",
  "Sufijo derivativo",
  "Morfema flexivo nominal (genero)",
  "Morfema flexivo nominal (numero)",
  "Vocal tematica",
  "Morfema flexivo verbal (tiempo/modo/aspecto)",
  "Morfema flexivo verbal (persona/numero)",
] as const;

const seSample = (partial: Omit<SeItem, "id" | "mode">): Omit<SeItem, "id" | "mode"> => partial;
const morfoSample = (partial: Omit<MorfoItem, "id" | "mode">): Omit<MorfoItem, "id" | "mode"> => partial;
const periphrasisSample = (partial: Omit<PeriphrasisItem, "id" | "mode">): Omit<PeriphrasisItem, "id" | "mode"> => partial;

export const SE_SAMPLE_BANK: Record<Difficulty, Array<Omit<SeItem, "id" | "mode">>> = {
  1: [
    seSample({
      sentence: "Marta se suele peinar cada manana.",
      difficulty: 1,
      seValue: "Reflexivo",
      seFunction: "CD",
      acceptedFunctions: ["CD"],
      verbalStructure: "Perifrasis verbal",
      periphrasisType: "Aspectual habitual",
      phraseType: "Oracion simple predicativa transitiva con perifrasis aspectual",
      explanation: "El sujeto realiza la accion sobre si mismo y la perifrasis 'soler + infinitivo' aporta valor habitual.",
    }),
    seSample({
      sentence: "Ana y Luis se abrazaron al llegar.",
      difficulty: 1,
      seValue: "Reciproco",
      seFunction: "CD",
      acceptedFunctions: ["CD"],
      verbalStructure: "Dos verbos",
      periphrasisType: "No aplica",
      phraseType: "Oracion simple predicativa transitiva",
      explanation: "La accion es mutua entre dos participantes y 'al llegar' introduce un segundo verbo, no una perifrasis.",
    }),
    seSample({
      sentence: "Se puede vivir bien aqui.",
      difficulty: 1,
      seValue: "Impersonal",
      seFunction: "Marca de impersonal",
      acceptedFunctions: ["Marca de impersonal", "Sin funcion sintactica propia"],
      verbalStructure: "Perifrasis verbal",
      periphrasisType: "Modal de posibilidad",
      phraseType: "Oracion simple impersonal con se y perifrasis modal",
      explanation: "No hay sujeto expreso ni recuperable y 'poder + infinitivo' funciona como perifrasis modal de posibilidad.",
    }),
    seSample({
      sentence: "Pablo se lava las manos antes de comer.",
      difficulty: 1,
      seValue: "Reflexivo",
      seFunction: "CD",
      acceptedFunctions: ["CD"],
      verbalStructure: "Dos verbos",
      periphrasisType: "No aplica",
      phraseType: "Oracion simple predicativa transitiva",
      explanation: "El sujeto realiza la accion sobre si mismo y 'comer' aparece en una subordinada final, no en una perifrasis.",
    }),
    seSample({
      sentence: "Marta se dio cuenta del error enseguida.",
      difficulty: 1,
      seValue: "Pronominal",
      seFunction: "Morfema verbal",
      acceptedFunctions: ["Morfema verbal", "Sin funcion sintactica propia"],
      verbalStructure: "Locucion verbal",
      periphrasisType: "No aplica",
      phraseType: "Oracion simple predicativa con locucion verbal pronominal",
      explanation: "En 'darse cuenta' el se forma parte de la locucion verbal y no desempena por si solo funcion de CD o CI.",
    }),
  ],
  2: [
    seSample({
      sentence: "La profesora se lo pudo explicar al grupo.",
      difficulty: 2,
      seValue: "Sustitucion (le -> se)",
      seFunction: "CI",
      acceptedFunctions: ["CI"],
      verbalStructure: "Perifrasis verbal",
      periphrasisType: "Modal de posibilidad",
      phraseType: "Oracion simple predicativa transitiva con doble complemento y perifrasis modal",
      explanation: "Se sustituye le/les por se delante de pronombres de CD y 'poder + infinitivo' crea una perifrasis modal.",
    }),
    seSample({
      sentence: "Pedro se echo a reir al final de la charla.",
      difficulty: 2,
      seValue: "Pronominal",
      seFunction: "Morfema verbal",
      acceptedFunctions: ["Morfema verbal", "Sin funcion sintactica propia"],
      verbalStructure: "Perifrasis verbal",
      periphrasisType: "Aspectual ingresiva",
      phraseType: "Oracion simple predicativa con perifrasis aspectual",
      explanation: "La construccion 'echarse a + infinitivo' indica comienzo repentino de la accion y el se forma parte del verbo pronominal.",
    }),
    seSample({
      sentence: "Se venden pisos en este barrio.",
      difficulty: 2,
      seValue: "Pasiva refleja",
      seFunction: "Marca de pasiva",
      acceptedFunctions: ["Marca de pasiva", "Sin funcion sintactica propia"],
      verbalStructure: "Verbo simple",
      periphrasisType: "No aplica",
      phraseType: "Oracion simple pasiva refleja",
      explanation: "El verbo concuerda con el sujeto paciente 'pisos'; se marca voz pasiva refleja.",
    }),
    seSample({
      sentence: "Mi tio se hizo cargo del traslado urgente.",
      difficulty: 2,
      seValue: "Pronominal",
      seFunction: "Morfema verbal",
      acceptedFunctions: ["Morfema verbal", "Sin funcion sintactica propia"],
      verbalStructure: "Locucion verbal",
      periphrasisType: "No aplica",
      phraseType: "Oracion simple predicativa con locucion verbal",
      explanation: "La locucion 'hacerse cargo de' incorpora el se como parte fija del verbo y no como complemento autonomo.",
    }),
    seSample({
      sentence: "Lucia se puso a quejarse del ruido del bar.",
      difficulty: 2,
      seValue: "Pronominal",
      seFunction: "Morfema verbal",
      acceptedFunctions: ["Morfema verbal", "Sin funcion sintactica propia"],
      verbalStructure: "Perifrasis verbal",
      periphrasisType: "Aspectual ingresiva",
      phraseType: "Oracion simple predicativa con verbo pronominal y perifrasis aspectual",
      explanation: "La estructura 'ponerse a + infinitivo' expresa inicio de la accion y el se pertenece al verbo pronominal.",
    }),
  ],
  3: [
    seSample({
      sentence: "Ayer se me pudo romper el portatil justo antes de la entrega.",
      difficulty: 3,
      seValue: "Accidental (dativo de interes)",
      seFunction: "CI",
      acceptedFunctions: ["CI"],
      verbalStructure: "Perifrasis verbal",
      periphrasisType: "Modal de posibilidad",
      phraseType: "Oracion simple predicativa con dativo de interes y perifrasis modal",
      explanation: "Se + dativo (me) expresa evento no intencional con afectacion del hablante y 'poder + infinitivo' introduce posibilidad.",
    }),
    seSample({
      sentence: "En este despacho se suele atender a los clientes sin cita previa.",
      difficulty: 3,
      seValue: "Impersonal",
      seFunction: "Marca de impersonal",
      acceptedFunctions: ["Marca de impersonal", "Sin funcion sintactica propia"],
      verbalStructure: "Perifrasis verbal",
      periphrasisType: "Aspectual habitual",
      phraseType: "Oracion simple impersonal con se y perifrasis aspectual",
      explanation: "El verbo queda en tercera persona singular, no hay sujeto referencial y 'soler + infinitivo' aporta habitualidad.",
    }),
    seSample({
      sentence: "Cuando termino la reunion, los socios se volvieron a felicitar por el acuerdo.",
      difficulty: 3,
      seValue: "Reciproco",
      seFunction: "CD",
      acceptedFunctions: ["CD"],
      verbalStructure: "Perifrasis verbal",
      periphrasisType: "Aspectual reiterativa",
      phraseType: "Oracion compuesta con subordinada temporal",
      explanation: "La accion de felicitarse es mutua entre los socios y 'volver a + infinitivo' expresa repeticion de la accion.",
    }),
    seSample({
      sentence: "La directora se dio cuenta de que faltaban varios informes esenciales.",
      difficulty: 3,
      seValue: "Pronominal",
      seFunction: "Morfema verbal",
      acceptedFunctions: ["Morfema verbal", "Sin funcion sintactica propia"],
      verbalStructure: "Locucion verbal",
      periphrasisType: "No aplica",
      phraseType: "Oracion compuesta con principal y subordinada sustantiva",
      explanation: "En la locucion 'darse cuenta de' el se forma parte fija del verbo y la subordinada funciona como termino de la preposicion.",
    }),
    seSample({
      sentence: "Aqui se acaba de premiar a quien trabaja con constancia cada trimestre.",
      difficulty: 3,
      seValue: "Impersonal",
      seFunction: "Marca de impersonal",
      acceptedFunctions: ["Marca de impersonal", "Sin funcion sintactica propia"],
      verbalStructure: "Perifrasis verbal",
      periphrasisType: "Aspectual terminativa",
      phraseType: "Oracion compuesta con principal impersonal",
      explanation: "La principal es impersonal con se y 'acabar de + infinitivo' aporta un valor aspectual terminativo o reciente.",
    }),
  ],
};

export const MORFO_SAMPLE_BANK: Record<Difficulty, Array<Omit<MorfoItem, "id" | "mode">>> = {
  1: [
    morfoSample({
      word: "gatos",
      difficulty: 1,
      wordType: "Sustantivo",
      lexeme: "gat",
      acceptedLexemes: ["gat", "gato"],
      morphemes: ["o", "s"],
      morphemeTypes: ["Morfema flexivo nominal (genero)", "Morfema flexivo nominal (numero)"],
      analysisType: "Sustantivo comun masculino plural",
      explanation: "Lexema gat + genero -o + numero -s.",
    }),
    morfoSample({
      word: "casas",
      difficulty: 1,
      wordType: "Sustantivo",
      lexeme: "cas",
      acceptedLexemes: ["cas", "casa"],
      morphemes: ["a", "s"],
      morphemeTypes: ["Morfema flexivo nominal (genero)", "Morfema flexivo nominal (numero)"],
      analysisType: "Sustantivo comun femenino plural",
      explanation: "Lexema cas + genero -a + numero -s.",
    }),
    morfoSample({
      word: "cantamos",
      difficulty: 1,
      wordType: "Verbo",
      lexeme: "cant",
      acceptedLexemes: ["cant", "canta"],
      morphemes: ["a", "mos"],
      morphemeTypes: ["Vocal tematica", "Morfema flexivo verbal (persona/numero)"],
      analysisType: "Verbo en primera persona plural",
      explanation: "Lexema cant + vocal tematica -a + marca de persona/numero -mos.",
    }),
    morfoSample({
      word: "injusto",
      difficulty: 1,
      wordType: "Adjetivo",
      lexeme: "just",
      acceptedLexemes: ["just", "justo"],
      morphemes: ["in", "o"],
      morphemeTypes: ["Prefijo derivativo", "Morfema flexivo nominal (genero)"],
      analysisType: "Adjetivo derivado masculino singular",
      explanation: "Prefijo derivativo in- + lexema just + marca de genero -o.",
    }),
    morfoSample({
      word: "amigas",
      difficulty: 1,
      wordType: "Sustantivo",
      lexeme: "amig",
      acceptedLexemes: ["amig", "amiga"],
      morphemes: ["a", "s"],
      morphemeTypes: ["Morfema flexivo nominal (genero)", "Morfema flexivo nominal (numero)"],
      analysisType: "Sustantivo comun femenino plural",
      explanation: "Lexema amig + genero -a + numero -s.",
    }),
  ],
  2: [
    morfoSample({
      word: "panadero",
      difficulty: 2,
      wordType: "Sustantivo",
      lexeme: "pan",
      acceptedLexemes: ["pan"],
      morphemes: ["ader", "o"],
      morphemeTypes: ["Sufijo derivativo", "Morfema flexivo nominal (genero)"],
      analysisType: "Sustantivo derivado",
      explanation: "Lexema pan + sufijo derivativo -ader- + marca de genero -o.",
    }),
    morfoSample({
      word: "desordenados",
      difficulty: 2,
      wordType: "Adjetivo",
      lexeme: "orden",
      acceptedLexemes: ["orden"],
      morphemes: ["des", "ad", "o", "s"],
      morphemeTypes: [
        "Prefijo derivativo",
        "Sufijo derivativo",
        "Morfema flexivo nominal (genero)",
        "Morfema flexivo nominal (numero)",
      ],
      analysisType: "Adjetivo con derivacion y flexion",
      explanation: "Prefijo des- + lexema orden + sufijo derivativo -ad- + flexivos -o y -s.",
    }),
    morfoSample({
      word: "jugadoras",
      difficulty: 2,
      wordType: "Sustantivo",
      lexeme: "jug",
      acceptedLexemes: ["jug", "juga"],
      morphemes: ["ador", "a", "s"],
      morphemeTypes: [
        "Sufijo derivativo",
        "Morfema flexivo nominal (genero)",
        "Morfema flexivo nominal (numero)",
      ],
      analysisType: "Sustantivo derivado femenino plural",
      explanation: "Lexema jug + derivativo -ador- + genero -a + numero -s.",
    }),
    morfoSample({
      word: "cantabais",
      difficulty: 2,
      wordType: "Verbo",
      lexeme: "cant",
      acceptedLexemes: ["cant", "canta"],
      morphemes: ["aba", "is"],
      morphemeTypes: [
        "Morfema flexivo verbal (tiempo/modo/aspecto)",
        "Morfema flexivo verbal (persona/numero)",
      ],
      analysisType: "Verbo en segunda persona plural",
      explanation: "Lexema cant + marca verbal -aba + marca de persona/numero -is.",
    }),
    morfoSample({
      word: "imposible",
      difficulty: 2,
      wordType: "Adjetivo",
      lexeme: "posibl",
      acceptedLexemes: ["posibl", "posible"],
      morphemes: ["im"],
      morphemeTypes: ["Prefijo derivativo"],
      analysisType: "Adjetivo con prefijacion",
      explanation: "Prefijo derivativo im- + lexema posibl.",
    }),
  ],
  3: [
    morfoSample({
      word: "inmovilizaciones",
      difficulty: 3,
      wordType: "Sustantivo",
      lexeme: "movil",
      acceptedLexemes: ["movil"],
      morphemes: ["in", "iza", "cion", "es"],
      morphemeTypes: [
        "Prefijo derivativo",
        "Sufijo derivativo",
        "Sufijo derivativo",
        "Morfema flexivo nominal (numero)",
      ],
      analysisType: "Sustantivo complejo con prefijacion y doble sufijacion",
      explanation: "in- + movil + -iza- + -cion + -es (plural).",
    }),
    morfoSample({
      word: "deshumanizadoras",
      difficulty: 3,
      wordType: "Adjetivo",
      lexeme: "human",
      acceptedLexemes: ["human"],
      morphemes: ["des", "iza", "dor", "a", "s"],
      morphemeTypes: [
        "Prefijo derivativo",
        "Sufijo derivativo",
        "Sufijo derivativo",
        "Morfema flexivo nominal (genero)",
        "Morfema flexivo nominal (numero)",
      ],
      analysisType: "Adjetivo derivado complejo",
      explanation: "des- + human + -iza- + -dor- + -a + -s.",
    }),
    morfoSample({
      word: "reconstruiriamos",
      difficulty: 3,
      wordType: "Verbo",
      lexeme: "constru",
      acceptedLexemes: ["constru", "construir"],
      morphemes: ["re", "iria", "mos"],
      morphemeTypes: [
        "Prefijo derivativo",
        "Morfema flexivo verbal (tiempo/modo/aspecto)",
        "Morfema flexivo verbal (persona/numero)",
      ],
      analysisType: "Verbo prefijado con flexion compuesta",
      explanation: "Prefijo re- + lexema constru + marca verbal -iria + persona/numero -mos.",
    }),
    morfoSample({
      word: "anticonstitucionales",
      difficulty: 3,
      wordType: "Adjetivo",
      lexeme: "constitucion",
      acceptedLexemes: ["constitucion", "constitucional"],
      morphemes: ["anti", "al", "es"],
      morphemeTypes: ["Prefijo derivativo", "Sufijo derivativo", "Morfema flexivo nominal (numero)"],
      analysisType: "Adjetivo prefijado plural",
      explanation: "anti- + lexema constitucion + sufijo -al + plural -es.",
    }),
    morfoSample({
      word: "precalentamientos",
      difficulty: 3,
      wordType: "Sustantivo",
      lexeme: "calent",
      acceptedLexemes: ["calent", "calentar"],
      morphemes: ["pre", "amiento", "s"],
      morphemeTypes: ["Prefijo derivativo", "Sufijo derivativo", "Morfema flexivo nominal (numero)"],
      analysisType: "Sustantivo derivado con prefijo y sufijo",
      explanation: "pre- + lexema calent + derivativo -amiento + plural -s.",
    }),
  ],
};

export const PERIPHRASIS_SAMPLE_BANK: Record<Difficulty, Array<Omit<PeriphrasisItem, "id" | "mode">>> = {
  1: [
    periphrasisSample({
      sentence: "Marta suele estudiar por la noche.",
      difficulty: 1,
      verbalStructure: "Perifrasis verbal",
      periphrasisType: "Aspectual habitual",
      phraseType: "Oracion simple predicativa",
      explanation: "'Soler + infinitivo' forma una perifrasis aspectual habitual.",
    }),
    periphrasisSample({
      sentence: "Luis echo a correr al oir el timbre.",
      difficulty: 1,
      verbalStructure: "Perifrasis verbal",
      periphrasisType: "Aspectual ingresiva",
      phraseType: "Oracion simple predicativa",
      explanation: "'Echarse a + infinitivo' indica inicio brusco de la accion.",
    }),
    periphrasisSample({
      sentence: "La jefa tuvo en cuenta tu consejo.",
      difficulty: 1,
      verbalStructure: "Locucion verbal",
      periphrasisType: "No aplica",
      phraseType: "Oracion simple predicativa",
      explanation: "'Tener en cuenta' funciona como una locucion verbal fija, no como perifrasis.",
    }),
    periphrasisSample({
      sentence: "Pedro salio y cerro la puerta.",
      difficulty: 1,
      verbalStructure: "Dos verbos",
      periphrasisType: "No aplica",
      phraseType: "Oracion compuesta coordinada",
      explanation: "Hay dos formas verbales plenas coordinadas, no una sola unidad verbal.",
    }),
    periphrasisSample({
      sentence: "El detective dio con la pista enseguida.",
      difficulty: 1,
      verbalStructure: "Locucion verbal",
      periphrasisType: "No aplica",
      phraseType: "Oracion simple predicativa",
      explanation: "'Dar con' es una locucion verbal con significado unitario.",
    }),
  ],
  2: [
    periphrasisSample({
      sentence: "Debes entregar el informe antes del viernes.",
      difficulty: 2,
      verbalStructure: "Perifrasis verbal",
      periphrasisType: "Modal obligativa",
      phraseType: "Oracion simple predicativa",
      explanation: "'Deber + infinitivo' expresa obligacion y forma una perifrasis modal.",
    }),
    periphrasisSample({
      sentence: "Puede llover con fuerza esta tarde.",
      difficulty: 2,
      verbalStructure: "Perifrasis verbal",
      periphrasisType: "Modal de posibilidad",
      phraseType: "Oracion simple predicativa",
      explanation: "'Poder + infinitivo' expresa posibilidad.",
    }),
    periphrasisSample({
      sentence: "La directora puso en marcha el plan de apoyo.",
      difficulty: 2,
      verbalStructure: "Locucion verbal",
      periphrasisType: "No aplica",
      phraseType: "Oracion simple predicativa",
      explanation: "'Poner en marcha' funciona como locucion verbal.",
    }),
    periphrasisSample({
      sentence: "El publico aplaudio y pidio otra cancion.",
      difficulty: 2,
      verbalStructure: "Dos verbos",
      periphrasisType: "No aplica",
      phraseType: "Oracion compuesta coordinada",
      explanation: "Aparecen dos verbos nucleares coordinados, no una perifrasis.",
    }),
    periphrasisSample({
      sentence: "Acaba de llegar el tren regional.",
      difficulty: 2,
      verbalStructure: "Perifrasis verbal",
      periphrasisType: "Aspectual terminativa",
      phraseType: "Oracion simple predicativa",
      explanation: "'Acabar de + infinitivo' forma una perifrasis aspectual.",
    }),
  ],
  3: [
    periphrasisSample({
      sentence: "Los tecnicos volvieron a revisar todo el sistema antes del cierre.",
      difficulty: 3,
      verbalStructure: "Perifrasis verbal",
      periphrasisType: "Aspectual reiterativa",
      phraseType: "Oracion simple predicativa",
      explanation: "'Volver a + infinitivo' expresa repeticion de la accion.",
    }),
    periphrasisSample({
      sentence: "La investigadora dio por validos los resultados tras la segunda prueba.",
      difficulty: 3,
      verbalStructure: "Locucion verbal",
      periphrasisType: "No aplica",
      phraseType: "Oracion simple predicativa",
      explanation: "'Dar por + adjetivo' se interpreta aqui como locucion verbal con sentido unitario.",
    }),
    periphrasisSample({
      sentence: "El portavoz termino la rueda de prensa y abandono el edificio sin responder.",
      difficulty: 3,
      verbalStructure: "Dos verbos",
      periphrasisType: "No aplica",
      phraseType: "Oracion compuesta coordinada",
      explanation: "Hay dos predicados coordinados con verbos plenos independientes.",
    }),
    periphrasisSample({
      sentence: "El laboratorio sigue buscando una vacuna mas estable para el invierno.",
      difficulty: 3,
      verbalStructure: "Perifrasis verbal",
      periphrasisType: "Aspectual durativa",
      phraseType: "Oracion simple predicativa",
      explanation: "'Seguir + gerundio' forma una perifrasis aspectual durativa.",
    }),
    periphrasisSample({
      sentence: "La delegada rompio a llorar cuando escucho la resolucion definitiva.",
      difficulty: 3,
      verbalStructure: "Perifrasis verbal",
      periphrasisType: "Aspectual ingresiva",
      phraseType: "Oracion compuesta con subordinada temporal",
      explanation: "'Romper a + infinitivo' expresa el comienzo repentino de la accion.",
    }),
  ],
};
