import type { ModelOption, Difficulty, MorfoItem, SeItem } from "./types";

export const MODEL_OPTIONS: ModelOption[] = [
  { label: "Gemini 2.5 Flash Lite", value: "gemini-2.5-flash-lite" },
  { label: "Gemini 2.5 Flash", value: "gemini-2.5-flash" },
  { label: "Gemini 2.5 Pro", value: "gemini-2.5-pro" },
  { label: "Gemini 2.0 Flash", value: "gemini-2.0-flash" },
  { label: "Gemini 2.0 Flash Exp", value: "gemini-2.0-flash-exp" },
  { label: "Gemini 2.0 Flash Lite", value: "gemini-2.0-flash-lite" },
  { label: "Gemma 3 1B IT", value: "gemma-3-1b-it" },
  { label: "Gemma 3 4B IT", value: "gemma-3-4b-it" },
  { label: "Gemma 3 12B IT", value: "gemma-3-12b-it" },
  { label: "Gemma 3 27B IT", value: "gemma-3-27b-it" },
];

export const SE_VALUES = [
  "Reflexivo",
  "Reciproco",
  "Sustitucion (le -> se)",
  "Pronominal",
  "Pasiva refleja",
  "Impersonal",
  "Accidental (dativo de interes)",
] as const;

export const SE_FUNCTIONS = [
  "CD",
  "CI",
  "Sin funcion sintactica propia",
  "Morfema verbal",
  "Marca de pasiva",
  "Marca de impersonal",
] as const;

export const MORFO_WORD_TYPES = ["Sustantivo", "Adjetivo", "Verbo", "Adverbio"] as const;

export const MORFO_MORPHEME_TYPES = [
  "Prefijo derivativo",
  "Interfijo",
  "Sufijo derivativo",
  "Morfema flexivo nominal (genero)",
  "Morfema flexivo nominal (numero)",
  "Vocal tematica",
  "Morfema flexivo verbal (tiempo/modo/aspecto)",
  "Morfema flexivo verbal (persona/numero)",
] as const;

const seSample = (partial: Omit<SeItem, "id" | "mode">): Omit<SeItem, "id" | "mode"> => partial;
const morfoSample = (partial: Omit<MorfoItem, "id" | "mode">): Omit<MorfoItem, "id" | "mode"> => partial;

export const SE_SAMPLE_BANK: Record<Difficulty, Array<Omit<SeItem, "id" | "mode">>> = {
  1: [
    seSample({
      sentence: "Marta se peina cada manana.",
      difficulty: 1,
      seValue: "Reflexivo",
      seFunction: "CD",
      acceptedFunctions: ["CD"],
      phraseType: "Oracion simple predicativa transitiva",
      explanation: "El sujeto realiza y recibe la accion sobre si mismo: Marta peina a Marta.",
    }),
    seSample({
      sentence: "Ana y Luis se abrazaron al llegar.",
      difficulty: 1,
      seValue: "Reciproco",
      seFunction: "CD",
      acceptedFunctions: ["CD"],
      phraseType: "Oracion simple predicativa transitiva",
      explanation: "La accion es mutua entre dos participantes: Ana abraza a Luis y Luis a Ana.",
    }),
    seSample({
      sentence: "Se vive bien aqui.",
      difficulty: 1,
      seValue: "Impersonal",
      seFunction: "Marca de impersonal",
      acceptedFunctions: ["Marca de impersonal", "Sin funcion sintactica propia"],
      phraseType: "Oracion simple impersonal con se",
      explanation: "No hay sujeto expreso ni recuperable; se marca impersonalidad.",
    }),
    seSample({
      sentence: "Pablo se lava las manos antes de comer.",
      difficulty: 1,
      seValue: "Reflexivo",
      seFunction: "CD",
      acceptedFunctions: ["CD"],
      phraseType: "Oracion simple predicativa transitiva",
      explanation: "El sujeto realiza la accion sobre si mismo.",
    }),
    seSample({
      sentence: "Se duerme mejor con silencio.",
      difficulty: 1,
      seValue: "Impersonal",
      seFunction: "Marca de impersonal",
      acceptedFunctions: ["Marca de impersonal", "Sin funcion sintactica propia"],
      phraseType: "Oracion simple impersonal con se",
      explanation: "No hay sujeto concreto, verbo en tercera persona singular.",
    }),
  ],
  2: [
    seSample({
      sentence: "La profesora se lo explico al grupo.",
      difficulty: 2,
      seValue: "Sustitucion (le -> se)",
      seFunction: "CI",
      acceptedFunctions: ["CI"],
      phraseType: "Oracion simple predicativa transitiva con doble complemento",
      explanation: "Se sustituye le/les por se delante de lo/la/los/las: le lo explico -> se lo explico.",
    }),
    seSample({
      sentence: "Pedro se arrepintio de su decision.",
      difficulty: 2,
      seValue: "Pronominal",
      seFunction: "Morfema verbal",
      acceptedFunctions: ["Morfema verbal", "Sin funcion sintactica propia"],
      phraseType: "Oracion simple predicativa con verbo pronominal",
      explanation: "Arrepentirse exige se como parte lexical del verbo, no como CD/CI autonomo.",
    }),
    seSample({
      sentence: "Se venden pisos en este barrio.",
      difficulty: 2,
      seValue: "Pasiva refleja",
      seFunction: "Marca de pasiva",
      acceptedFunctions: ["Marca de pasiva", "Sin funcion sintactica propia"],
      phraseType: "Oracion simple pasiva refleja",
      explanation: "El verbo concuerda con el sujeto paciente 'pisos'; se marca voz pasiva refleja.",
    }),
    seSample({
      sentence: "Mi tio se las entrego a la vecina.",
      difficulty: 2,
      seValue: "Sustitucion (le -> se)",
      seFunction: "CI",
      acceptedFunctions: ["CI"],
      phraseType: "Oracion simple predicativa transitiva con doble complemento",
      explanation: "Le/les cambia a se delante de pronombres de CD.",
    }),
    seSample({
      sentence: "Lucia se quejo del ruido del bar.",
      difficulty: 2,
      seValue: "Pronominal",
      seFunction: "Morfema verbal",
      acceptedFunctions: ["Morfema verbal", "Sin funcion sintactica propia"],
      phraseType: "Oracion simple predicativa con verbo pronominal",
      explanation: "Quejarse incorpora se como parte del verbo.",
    }),
  ],
  3: [
    seSample({
      sentence: "Ayer se me rompio el portatil justo antes de la entrega.",
      difficulty: 3,
      seValue: "Accidental (dativo de interes)",
      seFunction: "CI",
      acceptedFunctions: ["CI"],
      phraseType: "Oracion simple predicativa con dativo de interes",
      explanation: "Se + dativo (me) expresa evento no intencional con afectacion del hablante.",
    }),
    seSample({
      sentence: "En este despacho se atiende a los clientes sin cita previa.",
      difficulty: 3,
      seValue: "Impersonal",
      seFunction: "Marca de impersonal",
      acceptedFunctions: ["Marca de impersonal", "Sin funcion sintactica propia"],
      phraseType: "Oracion simple impersonal con se",
      explanation: "El verbo queda en tercera singular y no hay sujeto referencial concreto.",
    }),
    seSample({
      sentence: "Cuando termino la reunion, los socios se felicitaron por el acuerdo.",
      difficulty: 3,
      seValue: "Reciproco",
      seFunction: "CD",
      acceptedFunctions: ["CD"],
      phraseType: "Oracion compuesta con subordinada temporal",
      explanation: "La accion de felicitarse se realiza mutuamente entre varios sujetos.",
    }),
    seSample({
      sentence: "Se nos perdieron los documentos durante el traslado del archivo.",
      difficulty: 3,
      seValue: "Accidental (dativo de interes)",
      seFunction: "CI",
      acceptedFunctions: ["CI"],
      phraseType: "Oracion simple predicativa con dativo de interes",
      explanation: "Se expresa accidentalidad y afectacion con dativo.",
    }),
    seSample({
      sentence: "Aqui se premia a quien trabaja con constancia cada trimestre.",
      difficulty: 3,
      seValue: "Impersonal",
      seFunction: "Marca de impersonal",
      acceptedFunctions: ["Marca de impersonal", "Sin funcion sintactica propia"],
      phraseType: "Oracion compuesta con principal impersonal",
      explanation: "La principal es impersonal con se y hay subordinada de relativo.",
    }),
  ],
};

export const MORFO_SAMPLE_BANK: Record<Difficulty, Array<Omit<MorfoItem, "id" | "mode">>> = {
  1: [
    morfoSample({
      word: "gatos",
      difficulty: 1,
      wordType: "Sustantivo",
      lexeme: "gat",
      acceptedLexemes: ["gat", "gato"],
      morphemes: ["o", "s"],
      morphemeTypes: ["Morfema flexivo nominal (genero)", "Morfema flexivo nominal (numero)"],
      analysisType: "Sustantivo comun masculino plural",
      explanation: "Lexema gat + genero -o + numero -s.",
    }),
    morfoSample({
      word: "casas",
      difficulty: 1,
      wordType: "Sustantivo",
      lexeme: "cas",
      acceptedLexemes: ["cas", "casa"],
      morphemes: ["a", "s"],
      morphemeTypes: ["Morfema flexivo nominal (genero)", "Morfema flexivo nominal (numero)"],
      analysisType: "Sustantivo comun femenino plural",
      explanation: "Lexema cas + genero -a + numero -s.",
    }),
    morfoSample({
      word: "cantamos",
      difficulty: 1,
      wordType: "Verbo",
      lexeme: "cant",
      acceptedLexemes: ["cant", "canta"],
      morphemes: ["a", "mos"],
      morphemeTypes: ["Vocal tematica", "Morfema flexivo verbal (persona/numero)"],
      analysisType: "Verbo en primera persona plural",
      explanation: "Lexema cant + vocal tematica -a + marca de persona/numero -mos.",
    }),
    morfoSample({
      word: "injusto",
      difficulty: 1,
      wordType: "Adjetivo",
      lexeme: "just",
      acceptedLexemes: ["just", "justo"],
      morphemes: ["in", "o"],
      morphemeTypes: ["Prefijo derivativo", "Morfema flexivo nominal (genero)"],
      analysisType: "Adjetivo derivado masculino singular",
      explanation: "Prefijo derivativo in- + lexema just + marca de genero -o.",
    }),
    morfoSample({
      word: "amigas",
      difficulty: 1,
      wordType: "Sustantivo",
      lexeme: "amig",
      acceptedLexemes: ["amig", "amiga"],
      morphemes: ["a", "s"],
      morphemeTypes: ["Morfema flexivo nominal (genero)", "Morfema flexivo nominal (numero)"],
      analysisType: "Sustantivo comun femenino plural",
      explanation: "Lexema amig + genero -a + numero -s.",
    }),
  ],
  2: [
    morfoSample({
      word: "panadero",
      difficulty: 2,
      wordType: "Sustantivo",
      lexeme: "pan",
      acceptedLexemes: ["pan"],
      morphemes: ["ader", "o"],
      morphemeTypes: ["Sufijo derivativo", "Morfema flexivo nominal (genero)"],
      analysisType: "Sustantivo derivado",
      explanation: "Lexema pan + sufijo derivativo -ader- + marca de genero -o.",
    }),
    morfoSample({
      word: "desordenados",
      difficulty: 2,
      wordType: "Adjetivo",
      lexeme: "orden",
      acceptedLexemes: ["orden"],
      morphemes: ["des", "ad", "o", "s"],
      morphemeTypes: [
        "Prefijo derivativo",
        "Sufijo derivativo",
        "Morfema flexivo nominal (genero)",
        "Morfema flexivo nominal (numero)",
      ],
      analysisType: "Adjetivo con derivacion y flexion",
      explanation: "Prefijo des- + lexema orden + sufijo derivativo -ad- + flexivos -o y -s.",
    }),
    morfoSample({
      word: "jugadoras",
      difficulty: 2,
      wordType: "Sustantivo",
      lexeme: "jug",
      acceptedLexemes: ["jug", "juga"],
      morphemes: ["ador", "a", "s"],
      morphemeTypes: [
        "Sufijo derivativo",
        "Morfema flexivo nominal (genero)",
        "Morfema flexivo nominal (numero)",
      ],
      analysisType: "Sustantivo derivado femenino plural",
      explanation: "Lexema jug + derivativo -ador- + genero -a + numero -s.",
    }),
    morfoSample({
      word: "cantabais",
      difficulty: 2,
      wordType: "Verbo",
      lexeme: "cant",
      acceptedLexemes: ["cant", "canta"],
      morphemes: ["aba", "is"],
      morphemeTypes: [
        "Morfema flexivo verbal (tiempo/modo/aspecto)",
        "Morfema flexivo verbal (persona/numero)",
      ],
      analysisType: "Verbo en segunda persona plural",
      explanation: "Lexema cant + marca verbal -aba + marca de persona/numero -is.",
    }),
    morfoSample({
      word: "imposible",
      difficulty: 2,
      wordType: "Adjetivo",
      lexeme: "posibl",
      acceptedLexemes: ["posibl", "posible"],
      morphemes: ["im"],
      morphemeTypes: ["Prefijo derivativo"],
      analysisType: "Adjetivo con prefijacion",
      explanation: "Prefijo derivativo im- + lexema posibl.",
    }),
  ],
  3: [
    morfoSample({
      word: "inmovilizaciones",
      difficulty: 3,
      wordType: "Sustantivo",
      lexeme: "movil",
      acceptedLexemes: ["movil"],
      morphemes: ["in", "iza", "cion", "es"],
      morphemeTypes: [
        "Prefijo derivativo",
        "Sufijo derivativo",
        "Sufijo derivativo",
        "Morfema flexivo nominal (numero)",
      ],
      analysisType: "Sustantivo complejo con prefijacion y doble sufijacion",
      explanation: "in- + movil + -iza- + -cion + -es (plural).",
    }),
    morfoSample({
      word: "deshumanizadoras",
      difficulty: 3,
      wordType: "Adjetivo",
      lexeme: "human",
      acceptedLexemes: ["human"],
      morphemes: ["des", "iza", "dor", "a", "s"],
      morphemeTypes: [
        "Prefijo derivativo",
        "Sufijo derivativo",
        "Sufijo derivativo",
        "Morfema flexivo nominal (genero)",
        "Morfema flexivo nominal (numero)",
      ],
      analysisType: "Adjetivo derivado complejo",
      explanation: "des- + human + -iza- + -dor- + -a + -s.",
    }),
    morfoSample({
      word: "reconstruiriamos",
      difficulty: 3,
      wordType: "Verbo",
      lexeme: "constru",
      acceptedLexemes: ["constru", "construir"],
      morphemes: ["re", "iria", "mos"],
      morphemeTypes: [
        "Prefijo derivativo",
        "Morfema flexivo verbal (tiempo/modo/aspecto)",
        "Morfema flexivo verbal (persona/numero)",
      ],
      analysisType: "Verbo prefijado con flexion compuesta",
      explanation: "Prefijo re- + lexema constru + marca verbal -iria + persona/numero -mos.",
    }),
    morfoSample({
      word: "anticonstitucionales",
      difficulty: 3,
      wordType: "Adjetivo",
      lexeme: "constitucion",
      acceptedLexemes: ["constitucion", "constitucional"],
      morphemes: ["anti", "al", "es"],
      morphemeTypes: ["Prefijo derivativo", "Sufijo derivativo", "Morfema flexivo nominal (numero)"],
      analysisType: "Adjetivo prefijado plural",
      explanation: "anti- + lexema constitucion + sufijo -al + plural -es.",
    }),
    morfoSample({
      word: "precalentamientos",
      difficulty: 3,
      wordType: "Sustantivo",
      lexeme: "calent",
      acceptedLexemes: ["calent", "calentar"],
      morphemes: ["pre", "amiento", "s"],
      morphemeTypes: ["Prefijo derivativo", "Sufijo derivativo", "Morfema flexivo nominal (numero)"],
      analysisType: "Sustantivo derivado con prefijo y sufijo",
      explanation: "pre- + lexema calent + derivativo -amiento + plural -s.",
    }),
  ],
};
