export interface PhilosophyAnkiSeed {
  chapterId: string;
  chapterTitle: string;
  ankiId: number;
  question: string;
  answer: string;
}

// Mechanically extracted from the local Anki Philosophy deck. Keep wording verbatim.
export const PHILOSOPHY_ANKI_SEEDS: PhilosophyAnkiSeed[] = [
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770053149025,
    question: "Que es la racionalidad Teorica",
    answer: "Es quando utilizamos nuestro conocimiento para conocer la verdad. Sciencia y philosophy. \"SABER\"",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770053213627,
    question: "Que es la racionalidad Práctica",
    answer: "\"Saber Hacer\". Es quando aplicamos lo que conocemos a algo que utilizamos. eg: politica, etica etc..",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770053276953,
    question: "Que es un accion Inmanente",
    answer: "Es un accion que viene del interior del sujeto.\"por si mismo, de si mismo\"",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770053381182,
    question: "Porque el Conocimiento se dice \"Una acción inminente peculiar\"",
    answer: "el conocimiento\nproduce un efecto que no es externo, sino que queda en el interior del sujeto\nque conoce. Su peculiaridad consiste en que el objeto conocido pasa a\nformar parte del sujeto de un modo más íntimo que ninguna otra posesión\nmaterial.",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770053465147,
    question: "las 3 Características del conocimiento humano",
    answer: "Universalidad: A diferencia de los animales, el ser humano puede abstraer la experiencia concreta y comprender ideas universales aplicables a múltiples situaciones.\n\nApertura a todo lo real e infinitud: La inteligencia humana está abierta a toda la realidad y no tiene un límite final, ya que siempre puede seguir pensando y conociendo más.\n\nAlteridad: El ser humano es capaz de conocer la realidad como independiente de su mente y reflexionar sobre su propio acto de conocer.",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770053586304,
    question: "que es La estructura del conocimiento humano\nDice las 2 sensibilades y que hacen o contienen",
    answer: "La sensibilidad externa: Los 5 sentidos\nLa sensibilidad interna: Imaginacion y memoria trabajan juntos para dar continuidad a nuestros pensamientos etc...",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770053819231,
    question: "las 3 partes del conocimiento intelectual",
    answer: "La simple aprehensión: transformar algun experiencia etc... Personal en Leyes Universales \n\nEl Juicio: Separar 2 conceptos afirmando o negando una cosa\n\nEl Razonamiento: Ir de verdades Conocidas a verdades Desconocidas. \nPor deduccion etc..",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770053969119,
    question: "Explica el relación entre lenguaje y pensamiento. que permite el otro etc.. como se relacionan entre si mismos",
    answer: "El pensamiento humano suele estar mediado por el lenguaje y se expresa a través de palabras, pero no se identifica totalmente con ellas, ya que puede ir más allá de lo que el lenguaje logra expresar.",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770054081832,
    question: "Que es El giro gnoseológico del conocimiento",
    answer: "En la Edad Moderna se cuestionó el realismo medieval del conocimiento con la aparición de la nueva ciencia, que sustituyó a la ciencia aristotélica al basarse en la experimentación sensible y en la razón matemática para ordenar la realidad.",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770054239579,
    question: "Que es Racionalismo, que dice, que metodo, quien es el persona principal",
    answer: "Tiene su origen en la obra de René Descartes (1596-1650)\n\nExisten Ideas Innatas y la unica fuente del conocimiento es la razon.\n\nDuda Metodica: duda, genio maligno, Cogito,Ergo sum \nNO conocemos con certeza nuestras ideas",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770054359390,
    question: "Que es el Empirismo",
    answer: "2 principales representantes: David Hume y John Locke.\n\nUnica fuente del conocimiento es el experiencia. \n\nNo es posible, por tanto, un conocimiento de validez universal. La ciencia,\nlimitada a lo experimentable, no proporciona un saber verdadero, sino solo\nprobable.",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770054470641,
    question: "Que el Idealismo",
    answer: "Immanuel Kant: Idealismo trascendental\n\nConocemos al realidad como la mente la construye.\n\n\"Immanuel Kant propuso el idealismo trascendental, según el cual el conocimiento nace de la experiencia, pero solo alcanza a los fenómenos y no a la realidad en sí misma o noúmeno.\"",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770054598637,
    question: "Que es el realismo",
    answer: "Aristóteles (384-322 a. C.)\n\nPara el realismo de Aristóteles, conocer consiste en captar intencionalmente e inmaterialmente la realidad a partir de los sentidos, lo que permite a la inteligencia acceder a verdades universales que van más allá de la experiencia sensible.",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770054635344,
    question: "La verdad como adecuación del entendimiento con la cosa",
    answer: "la verdad consiste en la correspondencia entre lo que entiende la mente y lo que la cosa es en realidad.",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770054679633,
    question: "Que el la Verdad lógica",
    answer: "La verdad lógica reside en la mente y se da en el juicio, ya que un juicio es verdadero cuando lo que se afirma sobre una cosa se corresponde con la realidad y es falso cuando no lo hace.",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770054780535,
    question: "Que es La verdad ontológica",
    answer: "La verdad ontológica se refiere al ser propio de las cosas, que existen y son como son independientemente de que las conozcamos, y por ello constituye el fundamento de la verdad lógica, ya que es la mente la que debe adecuarse a la realidad.\n\n\"A rock has a certain nature, whether we think about it or not. When we understand it correctly logical truth arises\"",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770054965524,
    question: "Que es el escepticismo y sus 2 tipos",
    answer: "Esceptisismo dice que no hay ninguna verdad. Se autocontradice ya que decir que no hay ninguna verdad es una verdad.\n\nEscepticismo teórica, representada por Pirrón de Elis, que propone suspender todo juicio y ser indifferente\n\nEscepticismo práctica, vinculada al pragmatismo de William James, según el cual es verdadero aquello que resulta útil o tiene consecuencias prácticas positivas.",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770055129260,
    question: "que es La verdad como fruto del consenso",
    answer: "La verdad es un acuerdo entre personas debajo condiciones ideales: igualitario, Universal, no manipulado y racional.\n\n\"Jürgen Habermas defiende que la verdad depende del consenso alcanzado mediante un diálogo racional entre los sujetos, siempre que este se desarrolle bajo condiciones ideales de igualdad, universalidad y ausencia de manipulación.\"",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770055209373,
    question: "La certeza",
    answer: "es el estado mental en el que se afirma una proposición con plena seguridad, y se fundamenta en la evidencia del objeto sobre el que se juzga.",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770055258544,
    question: "La duda",
    answer: "es el estado mental en el que la mente vacila entre dos afirmaciones opuestas sin decidirse por ninguna de ellas.",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770055312049,
    question: "La opinión",
    answer: "Hipotesis no compueba. es el estado en el que se juzga algo sin plena adhesión mental, admitiendo que lo contrario de lo afirmado pueda ser verdadero.",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770055372028,
    question: "La Fe",
    answer: "Se basa en autoridad del otro y no basado en evidencia directa\n\nes un asentimiento firme y seguro que no se basa en la evidencia directa del objeto, sino en la voluntad movida por la autoridad o el testimonio de otra persona, y no se limita únicamente al ámbito religioso.",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770055523645,
    question: "La Ignorancia",
    answer: "Es la falta de conocimiento acerca de algo. Constituye un mal\ncuando lo que falta es un conocimiento que se debería tener.",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770055553045,
    question: "El Error",
    answer: "Consiste en afirmar lo falso como verdadero. El error implica la igno-\nrancia, pero se puede ser ignorante sin llegar a errar (basta con no formar\nningún juicio acerca de aquello que se ignora).",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770055608770,
    question: "la posverdad",
    answer: "Es un fenómeno social en el que, especialmente en el ámbito público, los hechos objetivos influyen menos en la formación de la opinión que las emociones, creencias personales o intereses, favoreciendo la manipulación del discurso con fines particulares.",
  },
  {
    chapterId: "tema-4",
    chapterTitle: "Tema 4",
    ankiId: 1770055693369,
    question: "El relativismo",
    answer: "La verdad es subjetiva\n\nFavorece la posverdad al sustituir los criterios objetivos de verdad por opiniones subjetivas o utilitarias, haciendo que los hechos pierdan importancia frente a creencias personales.",
  },
  {
    chapterId: "tema-7",
    chapterTitle: "Tema 7",
    ankiId: 1771515951840,
    question: "Que es la question fundamental que pregunta la metafisica?",
    answer: "Qué es la realidad ?",
  },
  {
    chapterId: "tema-7",
    chapterTitle: "Tema 7",
    ankiId: 1771516063668,
    question: "Que es la metafisica y que estudia ?",
    answer: "La metafísica es la ciencia primera, porque estudia las premisas o fundamentos sobre los que se construyen todas las demás ciencias.",
  },
  {
    chapterId: "tema-7",
    chapterTitle: "Tema 7",
    ankiId: 1771516340779,
    question: "¿Qué es el “ente”?",
    answer: "Un ente es todo aquello que existe.",
  },
  {
    chapterId: "tema-7",
    chapterTitle: "Tema 7",
    ankiId: 1771516758235,
    question: "Porque decimos que la metafisica es Universal y trascendental",
    answer: "1. Universal porque estudia todo la realidad.\n\n2. Transcendental porque va mas alla de las sciencias. Estudia el \"Ser\" que es aplicable a todo.",
  },
  {
    chapterId: "tema-7",
    chapterTitle: "Tema 7",
    ankiId: 1771516876597,
    question: "Que es la primer principio en que fundamos los sciencias ?",
    answer: "Principio de no contradicción:\n\nImpossible que lo mismo sea y no sea al mismo tiempo y en el mismo sentido.\n\nUna persona puede ser padre y no ser padre, pero no en el mismo sentido:\n\n- \nEs padre respecto a su hijo.\n\n- \nNo es padre respecto a su propio padre.\n\nNo hay contradicción porque el sentido es distinto.",
  },
  {
    chapterId: "tema-7",
    chapterTitle: "Tema 7",
    ankiId: 1771517022148,
    question: "Que es El principio de identidad",
    answer: "cada ente es lo que es; por tanto, es idéntico a si\nmismo y no es diferente de sí.",
  },
  {
    chapterId: "tema-7",
    chapterTitle: "Tema 7",
    ankiId: 1771517183431,
    question: "Qué es El principio de tercero excluido ?",
    answer: "Dice que:\n\nNo hay término medio entre el ser y el no ser.\n\nAlgo o es, o no es.\n\nEsto significa que entre una afirmación y su negación no existe una tercera posibilidad.",
  },
  {
    chapterId: "tema-7",
    chapterTitle: "Tema 7",
    ankiId: 1771517323789,
    question: "Qué es El principio de causalidad ?",
    answer: "todo lo que existe, pero podría no haber sido, no\nha podido darse el ser a sí mismo\n\nTiene una causa eg: Dios etc...",
  },
  {
    chapterId: "tema-7",
    chapterTitle: "Tema 7",
    ankiId: 1771517743134,
    question: "¿Qué significa que el ente sea análogo según Aristóteles?",
    answer: "Tiene un significado común, porque todo lo que existe es.\n\nPero se aplica de modo diverso, porque las cosas son de maneras diferentes",
  },
  {
    chapterId: "tema-7",
    chapterTitle: "Tema 7",
    ankiId: 1771518026077,
    question: "Que es el Acto y Potencia",
    answer: "Algo que ya es (acto).\n\nAlgo que puede llegar a ser (potencia).",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773491166622,
    question: "Inclinacion viviente",
    answer: "defendar la propia vida, mantenerla y optimizarla",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773491216631,
    question: "inclinacion animal",
    answer: "Mantener la especie, si hay hijos: Defenderlos y educarlos",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773491267888,
    question: "Inclinacion racional",
    answer: "Buscar la verdad a través de la inteligencia. Convivir en sociedad",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773491314906,
    question: "Sindéresis",
    answer: "El primer juicio práctico: Hacer el bien y no hacer el mal",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773491552447,
    question: "Prudencia",
    answer: "Utilizar la razon para decidir que es el correcto a hacer en un momento.\nO saber que es bien etc...",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773493071930,
    question: "Eudemonista",
    answer: "El la concepcion ética que dice que el objetivo es buscar la felicidad.\nGREEK: eudaimonia = felicidad",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773573618820,
    question: "Etica no Eudomonista",
    answer: "etica del deber, etica del discurso. Normalente buscan una etica universal",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773573652945,
    question: "Etica del deber Immanuel Kant",
    answer: "Es buscar una etica universal basado en que tienes que actuar por deber",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773573728893,
    question: "Que significa buscar una moral formal (etica del deber Immanuel Kant)",
    answer: "No importa el resultado sino porque lo haces. Actuar por deber, no actuar porque conforma con el deber",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773573811981,
    question: "Differencia entre Moral Heterónoma y Moral autonóma",
    answer: "Moral Heterónoma: moral desde el interior eg placer, sentimientos\nMoral autonóma: utilizar Razon : Etica aprioristica",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773573889682,
    question: "A que problema enfrenta el Etica del deber de Immanuel Kant (etica del discurso)",
    answer: "Como hay muchas culturas no se puede hacer un moral universal sin algun bias cultural. Por esto el etica universal viene de un dialogo entre personas",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773573930050,
    question: "Que son las 2 condiciones del etica de discurso",
    answer: "No bias cultural\nNo religion",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773574082151,
    question: "Hedonismo",
    answer: "Buscar el placer estatico(felicidad). Buscar el ataraxia",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773574148333,
    question: "Que son los 2 tipos de placer en el Hedonismo",
    answer: "Placer dinamico= Satisfacer una necesidad\nPlacer estatico= Felicidad, Ataraxia= sin perturbacion + ausencia de dolor",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773574240846,
    question: "Que es el Estoicismo y quien era su maximo representante",
    answer: "Vivir con razon, buscar armonia interior y el paz del alma. \nAutodominio\nMarcus aurelios, Zenón de Citio",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773574286616,
    question: "Etica de la Virtud",
    answer: "Contemplacion de la verdad es el maximo objetivo de la sociedad\n\nAristoteles",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773574311574,
    question: "Utilitarismo",
    answer: "Algo es bueno en que es util por la mayor nombre de personas",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1773574338936,
    question: "Emotivismo",
    answer: "Buscar buenas sensaciones y emociones",
  },
  {
    chapterId: "tema-8",
    chapterTitle: "Tema 8",
    ankiId: 1774709240426,
    question: "Estoicismo",
    answer: "presentado por Zenon de Citio y Marco Aurelio, es una vida donde actas con razón que se basa en esto, y también se busca una paz interior y se basa en el autodominio. Paz del alma",
  },
];
