import { createContext, createElement, useContext, type ReactNode } from "react";

export type UiLanguage = "en" | "es" | "fr";

export const DEFAULT_UI_LANGUAGE: UiLanguage = "es";

export const UI_LANGUAGE_OPTIONS: Array<{ value: UiLanguage; label: string }> = [
  { value: "en", label: "English" },
  { value: "es", label: "Espanol" },
  { value: "fr", label: "Francais" },
];

const ES_UI_TEXT = {
  locale: "es-ES",
  languageSettingsTitle: "Idioma",
  languageFieldLabel: "Idioma de la interfaz",
  languageHelp: "Cambia botones, navegacion y paneles. Los ejercicios y bancos no cambian.",
  exercises: "Ejercicios",
  sectionsAria: "Secciones",
  practice: "Practicar",
  history: "Historial",
  settings: "Ajustes",
  banks: "Bancos",
  dailyChallenge: "Reto diario",
  personalTimes: "Tiempos personales",
  sectionSe: "Valores del se",
  sectionPeriphrasis: "Perifrasis",
  sectionMorfo: "Morfologia",
  sectionSintaxis: "Sintaxis",
  sectionDerivative: "Derivative",
  sectionPhilosophy: "Filosofia",
  sectionCatalan: "Catalan",
  batchSize: "Cantidad del lote",
  exactBatchSize: "Cantidad exacta del lote",
  max: "Max.",
  noDataYet: "Sin datos todavia.",
  importJson: "Importar JSON",
  importPasted: "Importar pegado",
  uploadJson: "Subir JSON",
  clearBank: "Vaciar banco",
  bankCleared: "Banco vaciado.",
  invalidJson: "JSON no valido.",
  savedCount: (count: number) => `${count} guardados`,
  importResult: (saved: number, rejected: number, total: number) =>
    `Guardados ${saved} validos. Ignorados ${rejected} de ${total}.`,
  browserKey: "Clave local del navegador",
  showKey: "Mostrar clave",
  hideKey: "Ocultar clave",
  clearKey: "Borrar clave",
  dailySettingsHelp: "Elige que secciones entran y cuantas preguntas quieres de cada una.",
  includedSections: "Secciones incluidas",
  questionsPerSection: "Preguntas por seccion",
  noDailySections: "No hay secciones disponibles.",
  chooseDailySection: "Selecciona al menos una seccion para crear el reto diario.",
  optionalFilters: "Filtros opcionales",
  selectedCount: (count: number) => `${count} seleccionada${count === 1 ? "" : "s"}`,
  catalanDailyTitle: "Catalan en el reto diario",
  catalanDailyHelp: "Sin filtros guardados, Catalan usa todas las cartas disponibles de todos los decks.",
  decks: "Decks",
  sections: "Secciones",
  noCatalanDecks: "No hay decks de Catalan cargados.",
  noCatalanSections: "No hay secciones para los decks seleccionados.",
  profiles: "Perfiles",
  saveProfiles: "Guardar perfiles",
  profileForAll: "Perfil",
  profileForAllHelp: "Este perfil se usa en todos los ejercicios y en el reto diario.",
  saveProfile: "Guardar perfil",
  aiAndApi: "AI y API",
  customPeriphrasisTypes: "Tipos de perifrasis personalizados",
  customPeriphrasisHint: "Separados por comas. Se suman a la lista base.",
  customPeriphrasisPlaceholder: "Ej. Obligacion atenuada, enfatica",
  customManual: "Personalizado (manual)",
  customModel: "Modelo personalizado",
  saveAi: "Guardar AI",
  personalTimesHelp: "Borra los tiempos guardados del reto diario.",
  clearTimesConfirm: (count: number) => `Confirmo que quiero borrar ${count} registro${count === 1 ? "" : "s"} de tiempos`,
  clearPersonalTimes: "Borrar tiempos personales",
  mode: "Modo",
  personalized: "Personalizado",
  values: "Valores",
  structures: "Estructuras",
  types: "Tipos",
  weaknessWeight: "Peso debilidades",
  normalWeight: "Peso normal",
  newValue: "Nuevo valor",
  customValue: "Valor personalizado",
  add: "Anadir",
  addCustomType: "Anadir tipo personalizado",
  addType: "Anadir tipo",
  randomOrder: "Orden aleatorio",
  shufflePending: "Barajar pendientes",
  preparingBatch: "Preparando lote...",
  nextPhrase: "Siguiente frase",
  nextWord: "Siguiente palabra",
  nextFunction: "Siguiente funcion",
  generateBatch: "Generar lote",
  checkResponse: "Comprobar respuesta",
  review: "Revisar",
  reviewing: "Revisando...",
  ask: "Preguntar",
  asking: "Consultando...",
  saveSettings: "Guardar ajustes",
  resetHistory: "Resetear historial",
  showCorrection: "Mostrar correccion",
  showAnswer: "Mostrar respuesta",
  answer: "Respuesta",
  book: "Libro",
  philosophyChaptersAria: "Capitulos de filosofia",
  syllabus: "Temario",
  chapters: "Capitulos",
  allTopics: "Todos los temas",
  cardsCount: (count: number) => `${count} tarjeta${count === 1 ? "" : "s"}`,
  selectionLocked: "La seleccion queda fijada durante esta sesion.",
  reviewSession: "Sesion de repaso",
  prepareCards: "Prepara tus tarjetas",
  philosophySelectionSummary: (topics: number, cards: number) =>
    `Has seleccionado ${topics} tema${topics === 1 ? "" : "s"} con ${cards} tarjeta${cards === 1 ? "" : "s"} disponibles.`,
  philosophyRandomHelp: "Mezcla las tarjetas de todos los temas elegidos.",
  selectChapterToStart: "Selecciona al menos un capitulo para empezar.",
  startCards: (count: number) => `Empezar · ${count} tarjeta${count === 1 ? "" : "s"}`,
  philosophySourceNote: "Las tarjetas marcadas como Anki conservan literalmente el mazo local. Las demas proceden de los apartados indicados del libro.",
  sessionCompleted: "Sesion completada",
  reviewedCards: (count: number) => `Has repasado ${count} tarjeta${count === 1 ? "" : "s"}`,
  philosophyCompletedHelp: "Puedes repetir la misma seleccion o ajustar los capitulos y el tamano del lote.",
  repeatSession: "Repetir sesion",
  changeSelection: "Cambiar seleccion",
  cardProgress: (current: number, total: number) => `Tarjeta ${current} de ${total}`,
  progress: "Progreso",
  endSession: "Terminar",
  revealShortcut: "Espacio o Intro para revelar",
  reviewThenContinue: "Revisa la respuesta y continua cuando estes listo.",
  finalize: "Finalizar",
  generatePhraseStart: "Genera una frase para empezar.",
  generateWordStart: "Genera una palabra para empezar.",
  generateFunctionStart: "Genera una funcion para empezar.",
  manualBankEmpty: "Banco manual sin items validos para esta seccion.",
  incompleteBatch: "Lote incompleto.",
  profile: "Perfil",
  profileAndModel: "Perfil y modelo",
  geminiModel: "Modelo Gemini",
  gemmaActive: "Gemma activa.",
  hideHistory: "Ocultar historial",
  historyHidden: "Historial oculto para esta seccion.",
  showOnlyFailures: "Mostrar solo fallos",
  localLearningByProfile: "Aprendizaje local por perfil",
  localHistoryByProfile: "Historial local por perfil",
  totalAttempts: "Intentos totales",
  fullAccuracy: "Acierto completo",
  hardestValue: "Mas dificiles (valor)",
  hardestFunction: "Mas dificiles (funcion)",
  hardestStructure: "Mas dificiles (estructura)",
  hardestType: "Mas dificiles (tipo)",
  hardestMorpheme: "Mas dificiles (morfema)",
  bestValue: "Mejores (valor)",
  bestFunction: "Mejores (funcion)",
  bestStructure: "Mejores (estructura)",
  bestType: "Mejores (tipo)",
  bestMorpheme: "Mejores (morfema)",
  exactPerformanceValueFunction: "Rendimiento exacto por valor y funcion",
  exactPerformanceAxis: "Rendimiento exacto por eje",
  exactPerformanceTypeMorpheme: "Rendimiento exacto por tipo y morfema",
  mostMissedCombinations: "Combinaciones donde mas fallas",
  savedAttempts: "Intentos guardados",
  clearProfileHistoryConfirm: "Confirmo que quiero borrar todo el historial de este perfil",
  date: "Fecha",
  total: "Total",
  axis: "Eje",
  item: "Item",
  ok: "OK",
  failures: "Fallos",
  attempts: "Intentos",
  failRate: "Tasa fallo",
  pair: "Par",
  phrase: "Frase",
  word: "Palabra",
  function: "Funcion",
  derivative: "Derivada",
  expected: "Esperado",
  yourAnswer: "Tu respuesta",
  status: "Estado",
  exerciseMode: "Modo",
  dailyStartHelp: "El reto usa solo las secciones elegidas en Ajustes y avanza automaticamente entre ellas.",
  inBank: (count: number) => `${count} en banco`,
  todaySavedTime: (duration: string) => `Hoy ya hay un tiempo guardado: ${duration}.`,
  lastChallengeFinished: (duration: string) => `Ultimo reto terminado: ${duration} total.`,
  noQuestionsInBanks: "No hay preguntas en los bancos todavia.",
  start: "Empezar",
  next: "Siguiente",
  finish: "Finalizar",
  noQuestionAvailable: "No hay pregunta disponible para esta seccion.",
  timeChartAria: "Grafica de tiempos por dia",
  notEnoughDailyQuestions: (sections: string) => `Algunas secciones no tienen suficientes preguntas nuevas: ${sections}.`,
  apiKeyNeeded: "Pega una GEMINI_API_KEY valida en Ajustes si quieres respuestas desarrolladas.",
  correct: "Correcto",
  incorrect: "Incorrecto",
  gap: "Hueco",
  expectedLabel: "Esperado",
  noAccent: "sin acento",
  clicked: "Seleccionado",
  none: "ninguno",
  youTyped: "Has escrito",
};

export type UiText = typeof ES_UI_TEXT;

export const UI_TEXT = {
  es: ES_UI_TEXT,
  en: {
    locale: "en-US",
    languageSettingsTitle: "Language",
    languageFieldLabel: "Interface language",
    languageHelp: "Changes buttons, navigation, and panels. Exercises and banks stay unchanged.",
    exercises: "Exercises",
    sectionsAria: "Sections",
    practice: "Practice",
    history: "History",
    settings: "Settings",
    banks: "Banks",
    dailyChallenge: "Daily challenge",
    personalTimes: "Personal times",
    sectionSe: "Se values",
    sectionPeriphrasis: "Periphrasis",
    sectionMorfo: "Morphology",
    sectionSintaxis: "Syntax",
    sectionDerivative: "Derivative",
    sectionPhilosophy: "Philosophy",
    sectionCatalan: "Catalan",
    batchSize: "Batch size",
    exactBatchSize: "Exact batch size",
    max: "Max.",
    noDataYet: "No data yet.",
    importJson: "Import JSON",
    importPasted: "Import pasted",
    uploadJson: "Upload JSON",
    clearBank: "Clear bank",
    bankCleared: "Bank cleared.",
    invalidJson: "Invalid JSON.",
    savedCount: (count: number) => `${count} saved`,
    importResult: (saved: number, rejected: number, total: number) =>
      `Saved ${saved} valid. Ignored ${rejected} of ${total}.`,
    browserKey: "Local browser key",
    showKey: "Show key",
    hideKey: "Hide key",
    clearKey: "Clear key",
    dailySettingsHelp: "Choose which sections are included and how many questions you want from each one.",
    includedSections: "Included sections",
    questionsPerSection: "Questions per section",
    noDailySections: "No sections are available.",
    chooseDailySection: "Select at least one section to create the daily challenge.",
    optionalFilters: "Optional filters",
    selectedCount: (count: number) => `${count} selected`,
    catalanDailyTitle: "Catalan in the daily challenge",
    catalanDailyHelp: "With no saved filters, Catalan uses every available card from every deck.",
    decks: "Decks",
    sections: "Sections",
    noCatalanDecks: "No Catalan decks loaded.",
    noCatalanSections: "No sections for the selected decks.",
    profiles: "Profiles",
    saveProfiles: "Save profiles",
    profileForAll: "Profile",
    profileForAllHelp: "This profile is used for every exercise and the daily challenge.",
    saveProfile: "Save profile",
    aiAndApi: "AI and API",
    customPeriphrasisTypes: "Custom periphrasis types",
    customPeriphrasisHint: "Comma-separated. Added to the base list.",
    customPeriphrasisPlaceholder: "E.g. Soft obligation, emphatic",
    customManual: "Custom (manual)",
    customModel: "Custom model",
    saveAi: "Save AI",
    personalTimesHelp: "Delete saved daily challenge times.",
    clearTimesConfirm: (count: number) => `I confirm I want to delete ${count} time record${count === 1 ? "" : "s"}`,
    clearPersonalTimes: "Delete personal times",
    mode: "Mode",
    personalized: "Personalized",
    values: "Values",
    structures: "Structures",
    types: "Types",
    weaknessWeight: "Weakness weight",
    normalWeight: "Normal weight",
    newValue: "New value",
    customValue: "Custom value",
    add: "Add",
    addCustomType: "Add custom type",
    addType: "Add type",
    randomOrder: "Random order",
    shufflePending: "Shuffle pending",
    preparingBatch: "Preparing batch...",
    nextPhrase: "Next phrase",
    nextWord: "Next word",
    nextFunction: "Next function",
    generateBatch: "Generate batch",
    checkResponse: "Check answer",
    review: "Review",
    reviewing: "Reviewing...",
    ask: "Ask",
    asking: "Asking...",
    saveSettings: "Save settings",
    resetHistory: "Reset history",
    showCorrection: "Show correction",
    showAnswer: "Show answer",
    answer: "Answer",
    book: "Book",
    philosophyChaptersAria: "Philosophy chapters",
    syllabus: "Syllabus",
    chapters: "Chapters",
    allTopics: "All topics",
    cardsCount: (count: number) => `${count} card${count === 1 ? "" : "s"}`,
    selectionLocked: "The selection is locked during this session.",
    reviewSession: "Review session",
    prepareCards: "Prepare your cards",
    philosophySelectionSummary: (topics: number, cards: number) =>
      `You selected ${topics} topic${topics === 1 ? "" : "s"} with ${cards} available card${cards === 1 ? "" : "s"}.`,
    philosophyRandomHelp: "Mix cards from all selected topics.",
    selectChapterToStart: "Select at least one chapter to begin.",
    startCards: (count: number) => `Start · ${count} card${count === 1 ? "" : "s"}`,
    philosophySourceNote: "Cards marked Anki keep the exact wording from the local deck. The others come from the requested book sections.",
    sessionCompleted: "Session complete",
    reviewedCards: (count: number) => `You reviewed ${count} card${count === 1 ? "" : "s"}`,
    philosophyCompletedHelp: "You can repeat the same selection or adjust the chapters and batch size.",
    repeatSession: "Repeat session",
    changeSelection: "Change selection",
    cardProgress: (current: number, total: number) => `Card ${current} of ${total}`,
    progress: "Progress",
    endSession: "End",
    revealShortcut: "Press Space or Enter to reveal",
    reviewThenContinue: "Review the answer and continue when you are ready.",
    finalize: "Finish",
    generatePhraseStart: "Generate a phrase to start.",
    generateWordStart: "Generate a word to start.",
    generateFunctionStart: "Generate a function to start.",
    manualBankEmpty: "The manual bank has no valid items for this section.",
    incompleteBatch: "Incomplete batch.",
    profile: "Profile",
    profileAndModel: "Profile and model",
    geminiModel: "Gemini model",
    gemmaActive: "Gemma active.",
    hideHistory: "Hide history",
    historyHidden: "History hidden for this section.",
    showOnlyFailures: "Show failures only",
    localLearningByProfile: "Local learning by profile",
    localHistoryByProfile: "Local history by profile",
    totalAttempts: "Total attempts",
    fullAccuracy: "Full accuracy",
    hardestValue: "Hardest (value)",
    hardestFunction: "Hardest (function)",
    hardestStructure: "Hardest (structure)",
    hardestType: "Hardest (type)",
    hardestMorpheme: "Hardest (morpheme)",
    bestValue: "Best (value)",
    bestFunction: "Best (function)",
    bestStructure: "Best (structure)",
    bestType: "Best (type)",
    bestMorpheme: "Best (morpheme)",
    exactPerformanceValueFunction: "Exact performance by value and function",
    exactPerformanceAxis: "Exact performance by axis",
    exactPerformanceTypeMorpheme: "Exact performance by type and morpheme",
    mostMissedCombinations: "Most missed combinations",
    savedAttempts: "Saved attempts",
    clearProfileHistoryConfirm: "I confirm I want to delete this profile's entire history",
    date: "Date",
    total: "Total",
    axis: "Axis",
    item: "Item",
    ok: "OK",
    failures: "Failures",
    attempts: "Attempts",
    failRate: "Failure rate",
    pair: "Pair",
    phrase: "Phrase",
    word: "Word",
    function: "Function",
    derivative: "Derivative",
    expected: "Expected",
    yourAnswer: "Your answer",
    status: "Status",
    exerciseMode: "Mode",
    dailyStartHelp: "The challenge uses only the sections selected in Settings and moves through them automatically.",
    inBank: (count: number) => `${count} in bank`,
    todaySavedTime: (duration: string) => `A time is already saved for today: ${duration}.`,
    lastChallengeFinished: (duration: string) => `Last completed challenge: ${duration} total.`,
    noQuestionsInBanks: "There are no questions in the banks yet.",
    start: "Start",
    next: "Next",
    finish: "Finish",
    noQuestionAvailable: "No question is available for this section.",
    timeChartAria: "Daily time chart",
    notEnoughDailyQuestions: (sections: string) => `Some sections do not have enough new questions: ${sections}.`,
    apiKeyNeeded: "Paste a valid GEMINI_API_KEY in Settings if you want detailed answers.",
    correct: "Correct",
    incorrect: "Incorrect",
    gap: "Gap",
    expectedLabel: "Expected",
    noAccent: "no accent",
    clicked: "Clicked",
    none: "none",
    youTyped: "You typed",
  },
  fr: {
    locale: "fr-FR",
    languageSettingsTitle: "Langue",
    languageFieldLabel: "Langue de l'interface",
    languageHelp: "Change les boutons, la navigation et les panneaux. Les exercices et les banques restent inchanges.",
    exercises: "Exercices",
    sectionsAria: "Sections",
    practice: "Pratiquer",
    history: "Historique",
    settings: "Reglages",
    banks: "Banques",
    dailyChallenge: "Defi quotidien",
    personalTimes: "Temps personnels",
    sectionSe: "Valeurs de se",
    sectionPeriphrasis: "Periphrase",
    sectionMorfo: "Morphologie",
    sectionSintaxis: "Syntaxe",
    sectionDerivative: "Derivee",
    sectionPhilosophy: "Philosophie",
    sectionCatalan: "Catalan",
    batchSize: "Taille du lot",
    exactBatchSize: "Taille exacte du lot",
    max: "Max.",
    noDataYet: "Pas encore de donnees.",
    importJson: "Importer JSON",
    importPasted: "Importer le collage",
    uploadJson: "Televerser JSON",
    clearBank: "Vider la banque",
    bankCleared: "Banque videe.",
    invalidJson: "JSON non valide.",
    savedCount: (count: number) => `${count} enregistres`,
    importResult: (saved: number, rejected: number, total: number) =>
      `${saved} valides enregistres. ${rejected} ignores sur ${total}.`,
    browserKey: "Cle locale du navigateur",
    showKey: "Afficher la cle",
    hideKey: "Masquer la cle",
    clearKey: "Effacer la cle",
    dailySettingsHelp: "Choisis les sections incluses et le nombre de questions pour chacune.",
    includedSections: "Sections incluses",
    questionsPerSection: "Questions par section",
    noDailySections: "Aucune section disponible.",
    chooseDailySection: "Selectionne au moins une section pour creer le defi quotidien.",
    optionalFilters: "Filtres facultatifs",
    selectedCount: (count: number) => `${count} selectionnee${count === 1 ? "" : "s"}`,
    catalanDailyTitle: "Catalan dans le defi quotidien",
    catalanDailyHelp: "Sans filtres enregistres, Catalan utilise toutes les cartes disponibles de tous les decks.",
    decks: "Decks",
    sections: "Sections",
    noCatalanDecks: "Aucun deck de Catalan charge.",
    noCatalanSections: "Aucune section pour les decks selectionnes.",
    profiles: "Profils",
    saveProfiles: "Enregistrer les profils",
    profileForAll: "Profil",
    profileForAllHelp: "Ce profil est utilise pour tous les exercices et le defi quotidien.",
    saveProfile: "Enregistrer le profil",
    aiAndApi: "AI et API",
    customPeriphrasisTypes: "Types de periphrase personnalises",
    customPeriphrasisHint: "Separes par des virgules. Ajoutes a la liste de base.",
    customPeriphrasisPlaceholder: "Ex. Obligation douce, emphatique",
    customManual: "Personnalise (manuel)",
    customModel: "Modele personnalise",
    saveAi: "Enregistrer AI",
    personalTimesHelp: "Supprime les temps enregistres du defi quotidien.",
    clearTimesConfirm: (count: number) => `Je confirme vouloir supprimer ${count} temps enregistre${count === 1 ? "" : "s"}`,
    clearPersonalTimes: "Supprimer les temps personnels",
    mode: "Mode",
    personalized: "Personnalise",
    values: "Valeurs",
    structures: "Structures",
    types: "Types",
    weaknessWeight: "Poids des faiblesses",
    normalWeight: "Poids normal",
    newValue: "Nouvelle valeur",
    customValue: "Valeur personnalisee",
    add: "Ajouter",
    addCustomType: "Ajouter un type personnalise",
    addType: "Ajouter un type",
    randomOrder: "Ordre aleatoire",
    shufflePending: "Melanger les elements restants",
    preparingBatch: "Preparation du lot...",
    nextPhrase: "Phrase suivante",
    nextWord: "Mot suivant",
    nextFunction: "Fonction suivante",
    generateBatch: "Generer le lot",
    checkResponse: "Verifier la reponse",
    review: "Reviser",
    reviewing: "Revision...",
    ask: "Demander",
    asking: "Question en cours...",
    saveSettings: "Enregistrer les reglages",
    resetHistory: "Reinitialiser l'historique",
    showCorrection: "Afficher la correction",
    showAnswer: "Afficher la reponse",
    answer: "Reponse",
    book: "Livre",
    philosophyChaptersAria: "Chapitres de philosophie",
    syllabus: "Programme",
    chapters: "Chapitres",
    allTopics: "Tous les themes",
    cardsCount: (count: number) => `${count} carte${count === 1 ? "" : "s"}`,
    selectionLocked: "La selection est verrouillee pendant cette session.",
    reviewSession: "Session de revision",
    prepareCards: "Prepare tes cartes",
    philosophySelectionSummary: (topics: number, cards: number) =>
      `Tu as selectionne ${topics} theme${topics === 1 ? "" : "s"} avec ${cards} carte${cards === 1 ? "" : "s"} disponibles.`,
    philosophyRandomHelp: "Melange les cartes de tous les themes selectionnes.",
    selectChapterToStart: "Selectionne au moins un chapitre pour commencer.",
    startCards: (count: number) => `Commencer · ${count} carte${count === 1 ? "" : "s"}`,
    philosophySourceNote: "Les cartes marquees Anki conservent exactement le texte du deck local. Les autres viennent des sections demandees du livre.",
    sessionCompleted: "Session terminee",
    reviewedCards: (count: number) => `Tu as revise ${count} carte${count === 1 ? "" : "s"}`,
    philosophyCompletedHelp: "Tu peux repeter la meme selection ou ajuster les chapitres et la taille du lot.",
    repeatSession: "Repeter la session",
    changeSelection: "Modifier la selection",
    cardProgress: (current: number, total: number) => `Carte ${current} sur ${total}`,
    progress: "Progression",
    endSession: "Terminer",
    revealShortcut: "Espace ou Entree pour afficher",
    reviewThenContinue: "Relis la reponse et continue quand tu es pret.",
    finalize: "Terminer",
    generatePhraseStart: "Genere une phrase pour commencer.",
    generateWordStart: "Genere un mot pour commencer.",
    generateFunctionStart: "Genere une fonction pour commencer.",
    manualBankEmpty: "La banque manuelle n'a aucun element valide pour cette section.",
    incompleteBatch: "Lot incomplet.",
    profile: "Profil",
    profileAndModel: "Profil et modele",
    geminiModel: "Modele Gemini",
    gemmaActive: "Gemma actif.",
    hideHistory: "Masquer l'historique",
    historyHidden: "Historique masque pour cette section.",
    showOnlyFailures: "Afficher seulement les erreurs",
    localLearningByProfile: "Apprentissage local par profil",
    localHistoryByProfile: "Historique local par profil",
    totalAttempts: "Tentatives totales",
    fullAccuracy: "Reussite complete",
    hardestValue: "Plus difficiles (valeur)",
    hardestFunction: "Plus difficiles (fonction)",
    hardestStructure: "Plus difficiles (structure)",
    hardestType: "Plus difficiles (type)",
    hardestMorpheme: "Plus difficiles (morpheme)",
    bestValue: "Meilleurs (valeur)",
    bestFunction: "Meilleurs (fonction)",
    bestStructure: "Meilleurs (structure)",
    bestType: "Meilleurs (type)",
    bestMorpheme: "Meilleurs (morpheme)",
    exactPerformanceValueFunction: "Performance exacte par valeur et fonction",
    exactPerformanceAxis: "Performance exacte par axe",
    exactPerformanceTypeMorpheme: "Performance exacte par type et morpheme",
    mostMissedCombinations: "Combinaisons les plus manquees",
    savedAttempts: "Tentatives enregistrees",
    clearProfileHistoryConfirm: "Je confirme vouloir supprimer tout l'historique de ce profil",
    date: "Date",
    total: "Total",
    axis: "Axe",
    item: "Element",
    ok: "OK",
    failures: "Erreurs",
    attempts: "Tentatives",
    failRate: "Taux d'erreur",
    pair: "Paire",
    phrase: "Phrase",
    word: "Mot",
    function: "Fonction",
    derivative: "Derivee",
    expected: "Attendu",
    yourAnswer: "Ta reponse",
    status: "Etat",
    exerciseMode: "Mode",
    dailyStartHelp: "Le defi utilise uniquement les sections choisies dans Reglages et les enchaine automatiquement.",
    inBank: (count: number) => `${count} en banque`,
    todaySavedTime: (duration: string) => `Un temps est deja enregistre aujourd'hui : ${duration}.`,
    lastChallengeFinished: (duration: string) => `Dernier defi termine : ${duration} au total.`,
    noQuestionsInBanks: "Il n'y a pas encore de questions dans les banques.",
    start: "Commencer",
    next: "Suivant",
    finish: "Terminer",
    noQuestionAvailable: "Aucune question disponible pour cette section.",
    timeChartAria: "Graphique des temps par jour",
    notEnoughDailyQuestions: (sections: string) => `Certaines sections n'ont pas assez de nouvelles questions : ${sections}.`,
    apiKeyNeeded: "Colle une GEMINI_API_KEY valide dans Reglages si tu veux des reponses detaillees.",
    correct: "Correct",
    incorrect: "Incorrect",
    gap: "Trou",
    expectedLabel: "Attendu",
    noAccent: "sans accent",
    clicked: "Selectionne",
    none: "aucun",
    youTyped: "Tu as ecrit",
  },
} satisfies Record<UiLanguage, UiText>;

const UiLanguageContext = createContext<UiLanguage>(DEFAULT_UI_LANGUAGE);

export function isUiLanguage(value: unknown): value is UiLanguage {
  return UI_LANGUAGE_OPTIONS.some((option) => option.value === value);
}

export function getUiText(language: UiLanguage): UiText {
  return UI_TEXT[language];
}

export function UiTextProvider({ children, language }: { children: ReactNode; language: UiLanguage }) {
  return createElement(UiLanguageContext.Provider, { value: language }, children);
}

export function useUiText(): UiText {
  return UI_TEXT[useContext(UiLanguageContext)];
}
